package cli

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/overplane/overplane/internal/platform/color"
	"github.com/overplane/overplane/internal/platform/configloader"
	oplog "github.com/overplane/overplane/internal/platform/log"
	"github.com/overplane/overplane/internal/platform/serde/yamlcanon"
	"github.com/overplane/overplane/internal/project"
)

const configBanner = "Generated by overplane init. Safe to edit; re-run `overplane init` to validate.\n" +
	"yaml-language-server: $schema=" + project.SchemaURL

type initCommand struct{ r *Runner }

func (c initCommand) Name() string { return "init" }
func (c initCommand) Usage() string {
	return Binary + " init [--dir PATH] [--name NAME] [--description DESC] [--cache_dir DIR] [--specs_dir DIR]"
}

func initHelp() color.HelpSpec {
	return color.HelpSpec{
		Command:     "init",
		Usage:       Binary + " init [--dir PATH] [--name NAME] [--description DESC] [--cache_dir DIR] [--specs_dir DIR]",
		Description: "Initialize an Overplane project: create or validate overplane.yaml from default values.",
		Flags: []color.HelpFlag{
			{
				Name:        "--dir",
				Placeholder: "PATH",
				Description: "directory to initialize (default: current directory)",
			},
			{
				Name:        "--name",
				Placeholder: "NAME",
				Description: "project name for overplane.yaml when the file is created " +
					"(default: derived from the directory name)",
			},
			{
				Name:        "--description",
				Placeholder: "DESC",
				Description: "project description written to overplane.yaml when the file is created",
			},
			{
				Name:        "--cache_dir",
				Placeholder: "DIR",
				Description: "cache directory path written to overplane.yaml when the file is created",
			},
			{
				Name:        "--specs_dir",
				Placeholder: "DIR",
				Description: "specs directory path written to overplane.yaml when the file is created",
			},
		},
		Examples: []string{
			Binary + " init",
			Binary + " init --dir ./myproject",
			Binary + " init --name my-app --description \"My app.\"",
		},
	}
}

func (c initCommand) Run(ctx context.Context, args []string) error {
	if len(args) > 0 && isHelpToken(args[0]) {
		fmt.Fprint(c.r.Out, usage(initHelp()))
		return nil
	}
	st := &initState{r: c.r, log: oplog.FromContext(ctx)}
	opts, err := c.parseInitArgs(args)
	if err != nil {
		return err
	}
	st.dir = opts.dir
	st.overrides = opts.overrides
	if err := st.ensureConfig(); err != nil {
		return err
	}
	if _, err := st.loadConfig(); err != nil {
		return err
	}
	if err := st.ensureNotGitignored(); err != nil {
		return err
	}
	if err := st.ensureWritable(); err != nil {
		return err
	}
	st.summary()
	c.printNextSteps()
	return nil
}

type initOverrides struct {
	name        string
	description string
	cacheDir    string
	specsDir    string
}

type parsedInitArgs struct {
	dir       string
	overrides initOverrides
}

func (c initCommand) parseInitArgs(args []string) (parsedInitArgs, error) {
	fl := flag.NewFlagSet("init", flag.ContinueOnError)
	fl.SetOutput(c.r.Err)
	dir := fl.String("dir", "", "directory to initialize")
	name := fl.String("name", "", "project name")
	description := fl.String("description", "", "project description")
	cacheDir := fl.String("cache_dir", "", "cache directory")
	specsDir := fl.String("specs_dir", "", "specs directory")
	if err := fl.Parse(args); err != nil {
		return parsedInitArgs{}, UsageError("init: %v", err)
	}
	if fl.NArg() > 0 {
		return parsedInitArgs{}, UsageError("init takes no positional arguments")
	}
	target := *dir
	if target == "" {
		wd, err := os.Getwd()
		if err != nil {
			return parsedInitArgs{}, IOError(err)
		}
		target = wd
	}
	abs, err := filepath.Abs(target)
	if err != nil {
		return parsedInitArgs{}, IOError(err)
	}
	info, err := os.Stat(abs)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		return parsedInitArgs{}, IOError(fmt.Errorf("init directory %s: %w", abs, err))
	case err != nil:
		return parsedInitArgs{}, IOError(fmt.Errorf("init directory %s: %w", abs, err))
	case !info.IsDir():
		return parsedInitArgs{}, IOError(fmt.Errorf("init directory %s: not a directory", abs))
	}
	return parsedInitArgs{
		dir: abs,
		overrides: initOverrides{
			name:        *name,
			description: *description,
			cacheDir:    *cacheDir,
			specsDir:    *specsDir,
		},
	}, nil
}

// initState threads the working dir, logger, and mutation tracking through
// the init phases.
type initState struct {
	r         *Runner
	log       *slog.Logger
	dir       string
	overrides initOverrides
	mutated   bool
}

func (s *initState) configPath() string { return filepath.Join(s.dir, project.FileName) }

// rel renders path relative to the init working dir for log output; paths
// outside the dir (or unresolvable ones) fall back to the input.
func (s *initState) rel(path string) string {
	r, err := filepath.Rel(s.dir, path)
	if err != nil || strings.HasPrefix(r, "..") {
		return path
	}
	return r
}

func (s *initState) warn(msg, step, action, path string) {
	s.mutated = true
	s.log.Warn(msg, "step", step, "action", action, "path", s.rel(path))
}

func (s *initState) skip(msg, step, path string) {
	s.log.Debug(msg, "step", step, "action", "skipped", "path", s.rel(path))
}

func applyInitOverrides(cfg *project.Config, o initOverrides) {
	if o.name != "" {
		cfg.Project.Name = o.name
	}
	if o.description != "" {
		cfg.Project.Description = o.description
	}
	if o.cacheDir != "" {
		cfg.Dirs.Cache = o.cacheDir
	}
	if o.specsDir != "" {
		cfg.Dirs.Specs = o.specsDir
	}
}

func (s *initState) ensureConfig() error {
	path := s.configPath()
	if _, err := os.Stat(path); err == nil {
		s.skip("overplane.yaml present", "init-config", path)
		return nil
	} else if !errors.Is(err, fs.ErrNotExist) {
		return IOError(err)
	}
	cfg, err := project.Default(filepath.Base(s.dir))
	if err != nil {
		return InternalError(err)
	}
	applyInitOverrides(cfg, s.overrides)
	opts, err := project.YAMLDocumentOptions()
	if err != nil {
		return InternalError(err)
	}
	data, err := yamlcanon.MarshalPlainDocumentedWithBanner(configBanner, cfg, opts)
	if err != nil {
		return InternalError(err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return IOError(err)
	}
	s.warn("created overplane.yaml", "init-config", "created", path)
	return nil
}

func (s *initState) loadConfig() (*project.Config, error) {
	cfg, err := project.Load(s.configPath())
	if err == nil {
		s.skip("overplane.yaml valid", "init-config", s.configPath())
		return cfg, nil
	}
	var ve configloader.ValidationError
	if errors.As(err, &ve) {
		for _, p := range ve.Problems {
			fmt.Fprintf(s.r.Err, "%s: %s\n", p.Pointer, p.Message)
		}
		return nil, ValidationError(fmt.Errorf(
			"%s failed validation; fix the problems above or move the file aside and re-run %s init",
			project.FileName, Binary,
		))
	}
	var pathErr *fs.PathError
	if errors.As(err, &pathErr) {
		return nil, IOError(err)
	}
	return nil, ValidationError(fmt.Errorf("%s: %w", project.FileName, err))
}

func (s *initState) ensureNotGitignored() error {
	path := filepath.Join(s.dir, ".gitignore")
	data, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		s.skip(".gitignore absent", "init-gitignore", path)
		return nil
	}
	if err != nil {
		return IOError(err)
	}
	updated, removed := removeGitignoreEntry(data, project.FileName)
	if !removed {
		s.skip(project.FileName+" not ignored", "init-gitignore", path)
		return nil
	}
	if err := os.WriteFile(path, updated, 0o644); err != nil {
		return IOError(err)
	}
	s.warn("removed "+project.FileName+" from .gitignore", "init-gitignore", "removed", path)
	return nil
}

func removeGitignoreEntry(data []byte, entry string) ([]byte, bool) {
	lines := strings.Split(string(data), "\n")
	var out []string
	removed := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == entry || trimmed == "/"+entry {
			removed = true
			continue
		}
		out = append(out, line)
	}
	if !removed {
		return data, false
	}
	// Trim trailing blank lines left by removal.
	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
		out = out[:len(out)-1]
	}
	result := strings.Join(out, "\n")
	if len(result) > 0 {
		result += "\n"
	}
	return []byte(result), true
}

func (s *initState) ensureWritable() error {
	path := s.configPath()
	f, err := os.OpenFile(path, os.O_WRONLY, 0)
	if err != nil {
		return IOError(fmt.Errorf("working directory not writable: %w", err))
	}
	if err := f.Close(); err != nil {
		return IOError(err)
	}
	s.skip("working directory writable", "init-writable", s.dir)
	return nil
}

func (s *initState) summary() {
	if s.mutated {
		s.log.Info("project initialized", "path", s.dir)
		return
	}
	s.log.Info("project already initialized; overplane.yaml valid", "path", s.dir)
}

func (c initCommand) printNextSteps() {
	t := color.Table(c.r.Out)
	t.AppendHeader(table.Row{"Next step", "Description"})
	add := func(cmd, desc string) {
		t.AppendRow(table.Row{color.Sprint(4, cmd), desc})
	}
	add("$EDITOR "+project.FileName, "review and update project settings")
	add(Binary+" setup", "build the project's agent container image")
	add(Binary+" init ", "re-validate config after edits to overplane.yaml")
	t.Render()
}
